### ISSUE TITLE
It seems like that ncm2 doesn't have a satisfactory cooperation with autozimu/LanguageClient-neovim on import module for java.

### ISSUE THREAD

**Issue by cogig** [ncm2/ncm2#114]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS
arch linux 
(If you're using Linux, sharing a reproducible, vimrc minimized docker image,
can definitely help solving the issue)

### neovim `:version` output
v0.3.2-1016-gc16529afa    
### Minimal vimrc for reproducing the issue
```
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'

Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-tmux'
Plug 'ncm2/ncm2-path'
Plug 'fgrsnau/ncm2-otherbuf',
Plug 'ncm2/ncm2-ultisnips'
inoremap <silent> <expr> <CR> ncm2_ultisnips#expand_or("\<CR>", 'n')

let $NVIM_PYTHON_LOG_FILE="/tmp/nvim_log"
let $NVIM_PYTHON_LOG_LEVEL="DEBUG"
let g:python_host_skip_check=1
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_skip_check=1
let g:python3_host_prog = '/usr/bin/python3'

let g:ncm2#auto_popup=1
set completeopt=noselect,menuone,noinsert
autocmd InsertEnter * call ncm2#enable_for_buffer()
" au TextChangedI * call ncm2#auto_trigger()


function! Multiple_cursors_before()
    call ncm2#lock('vim-multiple-cursors')
endfunction

function! Multiple_cursors_after()
    call ncm2#unlock('vim-multiple-cursors')
endfunction

Plug 'autozimu/LanguageClient-neovim', {
  \ 'branch': 'next',
  \ 'do': 'bash install.sh',
  \ 'frozen': 1,
  \ }


let g:LanguageClient_serverCommands = {
    \ 'java': ['jdtls'],
    \ }
let g:LanguageClient_autoStart = 1
let g:LanguageClient_loadSettings = 1
set completefunc=LanguageClient#complete
set formatexpr=LanguageClient#textDocument_rangeFormatting_sync()
let g:LanguageClient_completionPreferTextEdit=1
let g:LanguageClient_hasSnippetSupport =0
let g:LanguageClient_diagnosticsEnable=0

```
### neovim `:messages` output when the error occurs
```
/home/cogig/.vim/plugged/ncm2-ultisnips/autoload/ncm2_ultisnips.vim|42| ncm2_ultisnips#_do_expand_completed[16]
|| provider#python3#Call[18]
|| Traceback (most recent call last):
||   File "<string>", line 1, in <module>
||   File "/home/cogig/.vim/plugged/ncm2-ultisnips/pythonx/ncm2_lsp_snippet/utils.py", line 10, in apply_additional_text_edits
||     apply_lsp_additional_text_edits(ud, lspitem)
||   File "/home/cogig/.vim/plugged/ncm2-ultisnips/pythonx/ncm2_lsp_snippet/utils.py", line 33, in apply_lsp_additional_text_edits
||     additional_text_edits = resolved.get('additionalTextEdits', None)
|| Error detected while processing function
/home/cogig/.vim/plugged/ncm2-ultisnips/autoload/ncm2_ultisnips.vim|42| ncm2_ultisnips#_do_expand_completed[16]
|| provider#python3#Call[18]
|| AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by cogig** [comment]
I'm sorry for unspecific description.You can try `import java.awt.print` and the error will occur.

**Comment by cogig** [comment]
Here is error log.
https://gist.github.com/cogig/f39ccf46e8ae6368d413ea1ccb5bcdf0

**Comment by roxma** [comment]
There's no completion started according to the log files.

You need to reproduce the issue before posting the log files. Only `nvim_log_py3_ncm2_core` is needed.

**Comment by cogig** [comment]
I'm sorry that i may not understand what you mean.I just reproduced the error and uploaded nvim_log_py3_ncm2_core again.But I'm not sure if useful information that you need exists in nvim_log_py3_ncm2_core.

**Comment by roxma** [comment]
The log file still shows that there's no completion started.  Note that if you start neovim twice and both you enable logging both times, the log file will get overwritten.

BTW, You could tail the log file and see what's going on before posting it.

**Comment by pittcat** [comment]
@cogig The problem you encountered  may look like this according to your description.
https://asciinema.org/a/vp3iS0hvgqnplxNSTQHLtRkh4
We may come up against the same problem.But I'm not sure if the bug is belong to ncm2.Because ncm2 works well with pyls and other language servers.

**Comment by pittcat** [comment]
I just have a try for coc.nvim.The experience for language server may be more comfortable than ncm2 and lcn.

**Comment by roxma** [comment]
I have reproduced the error just now.

https://gist.github.com/roxma/d64bde9bb5b9cd1ef4db378e281ccd0e

I believe this is jdtls issue.

// cc @autozimu 

highlights in the log:

```
12:01:40 INFO main src/vim.rs:93 => Some("java") {"jsonrpc":"2.0","method":"completionItem/resolve","params":{"data":{"pid":"0","rid":"0","uri":"file:///home/roxma/work/ncm2-ws/language-server-protocol-inspector/HelloWorld.java"},"kind":9,"label":"java.awt.print","sortText":"999999151"},"id":53}
12:01:40 INFO reader-java src/vim.rs:396 <= Some("java") {"jsonrpc":"2.0","id":53,"error":{"code":-32603,"message":"Internal error.","data":"java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n\tat org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:83)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)\n\t... 12 more\nCaused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Invalid completion proposal\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\nCaused by: java.lang.IllegalStateException: Invalid completion proposal\n\tat org.eclipse.jdt.ls.core.internal.handlers.CompletionResolveHandler.resolve(CompletionResolveHandler.java:83)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$6(JDTLanguageServer.java:490)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\t... 6 more\n"}}
12:01:40 ERROR main src/vim.rs:58 ErrorMessage { msg: "Internal error." }
12:01:40 ERROR main src/vim.rs:60 Error handling message: Internal error.

Message: {"jsonrpc":"2.0","method":"completionItem/resolve","params":{"bufnr":1,"completionItem":{"data":{"pid":"0","rid":"0","uri":"file:///home/roxma/work/ncm2-ws/language-server-protocol-inspector/HelloWorld.java"},"kind":9,"label":"java.awt.print","sortText":"999999151"},"handle":false,"languageId":"java"},"id":5}

Error: ErrorMessage { msg: "Internal error." }
```
-----------------

By the way, this is not enough for completion engine to determin the right possition for the completion. it pops `java.awt.print` for `java.awt.`, but it also pops `out` for  `System.`, due to the `.`, this is ambigous for completion engine to determine how to properly insert the completion.

A proper textEdit is needed in this case.

```
{"jsonrpc":"2.0","id":21,"result":{"isIncomplete":false,"items":[{"label":"java.awt.print","kind":9,"sortText":"999999151","data":{"pid":"0","rid":"0","uri":"file:///home/roxma/work/ncm2-ws/language-server-protocol-inspector/HelloWorld.java"}},{"label":"PrintJob - java.awt","kind":7,"sortText":"999999372","filterText":"PrintJob","insertText":"PrintJob","data":{"decl_signature":"Ljava.awt.PrintJob;","pid":"1","rid":"0","uri":"file:///home/roxma/work/ncm2-ws/language-server-protocol-inspector/HelloWorld.java"}},{"label":"PrintGraphics - java.awt","kind":7,"sortText":"999999372","filterText":"PrintGraphics","insertText":"PrintGraphics","data":{"decl_signature":"Ljava.awt.PrintGraphics;","pid":"2","rid":"0","uri":"file:///home/roxma/work/ncm2-ws/language-server-protocol-inspector/HelloWorld.java"}}]}}
```

**Comment by roxma** [comment]
I have updated ncm2-ultisnips. The resolve error has been ignored.

**Comment by roxma** [comment]
@pittcat 

> I think ncm2 should draw some lessons from coc.nvim on language server.

Could you elaborate? I don't use language server myself. I'm not sure which part could be improved.

**Comment by pittcat** [comment]
因为害怕叙述不清楚，这里还是用中文叙述和动图尽量展现，希望@roxma可以谅解。
1. 关于snippets 的处理
感觉coc.nvim 对snippets 的expand是在你的输入以后去完成，ncm2 的话感觉不是这样的，那python 来举例，输入 `if` 这个时候coc.nvim 的补全菜单只有`if`,但是ncm2 的补全菜单会显示两个`if` 一个是`snippets` 一个是`keyword`,这是因为ncm2-ultisnips ncm2_lsp_snippet的作用，但这是ncm2 比较好的地方，但是同时也需要更多的判断去执行。这也造成了一种ncm2 有点不如coc 流畅的感觉。不知道有不有方案可以让ncm2 也可以像coc.nvim 那样把snippets 的expand 放到之后去的感觉。
2. javascript 相关的补全
javascript language server 是可用度比较差的,比如javascript-typescript-langserver，这个coc.nvim 写了基于 tsserver 的coc-tsserver ，这个不是ncm2 的问题，ncm2-tern 用起来也能用，只是coc 的js体验确实要好一些。
3. java import module 的时候
[coc.nvim](https://asciinema.org/a/6FYP55vGRK7QgnaFWBTSMMzoD)
[ncm2](https://asciinema.org/a/I3ZfIUBfzhgbvwmVxvz8IWXcQ)

**Comment by pittcat** [comment]
其实ncm2 和lcn 的配合还是很不错了，刚才测试和 ccls 搭配使用的时候，发现ccls 在和 coc.nvim 一起使用的时候还有几次出现2000ms 的延迟信息，但是ccls 和ncm2 lcn 搭配使用的时候都是很正常的。感觉很多问题确实不是ncm2 的问题。

**Comment by roxma** [comment]
> 1. 关于snippets 的处理

I'll confirm this issue later.

> 2. javascript 相关的补全

As mentioned in https://github.com/ncm2/ncm2/issues/114#issuecomment-450464725 , this is out of scope.

> 3. java import module 的时候,lsp 用 jdtls

https://github.com/neoclide/coc-java/blob/1cf0bc9ea832d0a5e331a5ec1719e14ae7e99f40/src/index.ts#L86

```typescript
          let isModule = items.length > 0 && items.every(o => o.kind == CompletionItemKind.Module)
          if (isModule) {
            result.startcol = doc.fixStartcol(position, ['.'])
          }
```

This is similar to the `2. javascript 相关的补全` issue you mentioned.

I think someone could open an issue to https://github.com/eclipse/eclipse.jdt.ls

As mentioned in https://github.com/ncm2/ncm2/issues/114#issuecomment-450464360 . 

> A proper textEdit is needed in this case.

// cc @fbricon

**Comment by roxma** [comment]
You could use this config as a workaround for the jdtls import completion:

```vim
call ncm2#override_source('LanguageClient_java', {'word_pattern': '(\w+|(?<=^import\s).*)'})
```

 `:help ncm2-word_pattern` for more information.

**Comment by pittcat** [comment]
@roxma After adding ```call ncm2#override_source('LanguageClient_java', {'word_pattern': '(\w+|(?<=^import\s).*)'})```  to my vimrc,the disdance of lsp experience  still exists in comparison to coc-java.Indeed idea is more reasonable choice for java.I just want to use vim for java when doing some algorithm practice.You  need not spend time on some lsp bugs.As the language servers grow mature,many bugs that don't belong to ncm2 will be fixed.

**Comment by pittcat** [comment]
@roxma python 的补全我是用的ncm2-jedi,pyls 用起来真的难受，抱歉这里的snippets对比也许有点不严谨。你可以试试ncm2 lcn ccls 和coc.nvim ccls 的对比，不知道是不是幻觉，coc.nvim 用起来有点丝滑的体验，ncm2 的体验也很好，但是感觉有点区别。

**Comment by pittcat** [comment]
不用试了ccls 了，我刚才试了一下，ncm2 ccls 和coc.nvim ccls 没法好好对比lsp 的snippets。应该分别对比ncm2 coc.nvim 和SirVer/ultisnips。我又分别试了一下，体验上差距很小。抱歉，确实是说不出明显的差距。但是我也不能确定是不是心理作用，ncm2 和 coc 的对snippets 的处理又给人一种有所不同的感觉。

**Comment by roxma** [comment]
@pittcat 

基于我个人的体验, ultisnips 比较慢, 猜测是因为其实现大量地 python 和 vim 直接互相调用. 在 neovim 里 python 是独立进程, rpc 调用的开销被放大.

这个问题在 vim8 上不存在.

基于个人体验, 我更喜欢纯 vimscript 的 snipmate 而不是 ultisnips. 然而大部分人更喜欢 ultisnips.

**Comment by pittcat** [comment]
@roxma 改天我试试切到snipmate 。感谢回复和对ncm2 的维护:smile:
