### ISSUE TITLE
[ncm2_jedi@yarp] KeyError: 'time' 

### ISSUE THREAD

**Issue by LaBatata101** [ncm2/ncm2#45]
### OS
Manjaro Linux 32 bit
Kernel: 4.9.115-1-MANJARO

### neovim `:version` output
```
NVIM v0.3.1                                                                      
Build type: Release                                                              
LuaJIT 2.0.5                                                                     
Compilation: /usr/bin/cc -march=i686 -mtune=generic -O2 -pipe -fstack-protector-s
trong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedanti
c -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wv
la -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_
GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_
VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I
/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/in
clude                                                                            
Compilado por builduser                                                          
                                                                                 
Features: +acl +iconv +jemalloc +tui                                             
See ":help feature-compile"                                                      
                                                                                 
    arquivo vimrc de sistema: "$VIM/sysinit.vim"                                 
            padrão para $VIM: "/usr/share/nvim"                                  
                                                                                 
Run :checkhealth for more info
```

### Minimal vimrc for reproducing the issue
```
call plug#begin('~/.config/nvim/plugged')
Plug 'ncm2/ncm2-jedi'                                                        
Plug 'ncm2/ncm2'                                                             
Plug 'roxma/nvim-yarp'
filetype plugin indent on                                  
call plug#end() 

let g:python3_host_prog = '/usr/bin/python'

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"                     
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"                 
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"

autocmd BufEnter * call ncm2#enable_for_buffer()                             
set completeopt=noinsert,menuone,noselect
```

### neovim `:messages` output when the error occurs
```
[ncm2_jedi@yarp] error caught in notification handler 'on_complete [{'filepath': '/home/labatata101/teste.py', 'typed': 'imp', 
'scope_match': 'python', 'startccol': 1, 'scope_level': 1, 'word_pattern': '(-?\\d*\\.\\d\\w*)|([^\\`\\~\\!\\@\\#\\$\\%\\^\\&\\
*\\(\\)\\-\\=\\+\\[\\{\\]\\}\\\\\\|\\;\\:\\\'\\"\\,\\.\\<\\>\\/\\?\\s]+)', 'lnum': 1, 'bufnr': 3, 'changedtick': 9, 'manual': 0
, 'base': 'imp', 'ccol': 4, 'filetype': 'python', 'curpos': [0, 1, 4, 0, 4], 'tick': [[0, 1, 4], 0], 'early_cache': False, 'con
text_id': 23, 'scope': 'python', 'matcher': {'name': 'abbrfuzzy'}, 'source': {'subscope_enable': 1, 'early_cache': 0, 'name': '
jedi', 'scope': ['python'], 'mark': 'py', 'on_warmup': 'ncm2_jedi#on_warmup', 'complete_pattern': ['^\\s*(import|from).*\\s', '
\\.', '\\(\\s?', ',\\s?'], 'enable': 1, 'auto_popup': 1, 'priority': 9, 'on_complete': 'ncm2_jedi#on_complete'}, 'bcol': 4, 'ma
tch_end': 0}, ['imp', '', 'def group(fun):', '    def wrapper(*args, **kwargs):', '        fun(*args, **kwargs)', "        prin
t('var', args)", '@group', 'def teste(s, ss):', '    return s + ss', '', '', 'print(teste(2, 2))', '']]'                       
[ncm2_jedi@yarp] Traceback (most recent call last):                                                                            
[ncm2_jedi@yarp]   File "/home/labatata101/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py", line 30, in on_notification        
[ncm2_jedi@yarp]     getattr(module_obj, method)(*args)                                                                        
[ncm2_jedi@yarp]   File "/home/labatata101/.config/nvim/plugged/ncm2/pythonx/ncm2.py", line 203, in on_complete                
[ncm2_jedi@yarp]     if not self.lazy_check_context(context):                                                                  
[ncm2_jedi@yarp]   File "/home/labatata101/.config/nvim/plugged/ncm2/pythonx/ncm2.py", line 80, in lazy_check_context          
[ncm2_jedi@yarp]     return lazy_check_context(self.nvim, context)                                                             
[ncm2_jedi@yarp]   File "/home/labatata101/.config/nvim/plugged/ncm2/pythonx/ncm2.py", line 70, in lazy_check_context          
[ncm2_jedi@yarp]     if now >= context['time'] + 0.5:                                                                          
[ncm2_jedi@yarp] KeyError: 'time'
```

**Comment by roxma** [comment]
Hmm...

Cannot reproduce.
