### ISSUE TITLE
[ncm2_core@yarp] KeyError: 'NVIM_YARP_MODULE'

### ISSUE THREAD

**Issue by liuchengxu** [ncm2/ncm2#8]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS
macOS 10.13.5

### neovim `:version` output

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_U
NIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack
-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180
612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/buil
d/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
编译者 brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.3.0/share/nvim"
```
### Minimal vimrc for reproducing the issue

```vim
runtime! defaults.vim
call plug#begin('~/.vim/plugged')
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
call plug#end()

set completeopt=noinsert,menuone,noselect

autocmd BufEnter * call ncm2#enable_for_buffer()

inoremap <expr> <CR> pumvisible() ? "\<c-y>\<cr>" : "\<CR>"
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

```
处理 function ncm2#enable_for_buffer[13]..<SNR>26_warmup[4]..<SNR>26_try_rnotify 时发生错误:
第    7 行:
E716: Dictionary 中不存在键: try_notify, [a:event, data] + a:000, s:core)
E116: Invalid arguments for function call
E15: 无效的表达式: call(s:core.try_notify, [a:event, data] + a:000, s:core)
[ncm2_core@yarp] Traceback (most recent call last):
[ncm2_core@yarp]   File "/Users/xlc/.vim/plugged/nvim-yarp/pythonx/yarp.py", line 33, in <module>
[ncm2_core@yarp]     module_obj = importlib.import_module(module)
[ncm2_core@yarp]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_mod
ule
[ncm2_core@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm2_core@yarp]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[ncm2_core@yarp]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[ncm2_core@yarp]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[ncm2_core@yarp]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[ncm2_core@yarp]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[ncm2_core@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm2_core@yarp]   File "/Users/xlc/.vim/plugged/ncm2/pythonx/ncm2_core.py", line 13, in <module>
[ncm2_core@yarp]     assert environ['NVIM_YARP_MODULE'] == 'ncm2_core'
[ncm2_core@yarp]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
[ncm2_core@yarp]     raise KeyError(key) from None
[ncm2_core@yarp] KeyError: 'NVIM_YARP_MODULE'
[ncm2_core@yarp] Job is dead. cmd=['/usr/local/opt/python/bin/python3.7', '-u', '/Users/xlc/.vim/plugged/nvim-yarp/pythonx/yarp.py', '/var/folders/33/04x06z_n
0bqcdjy_kd6jst380000gn/T/nvimKFJIYS/0', 2, 'ncm2_core']
```

My understanding is that something is wrong with my local environment, since I have confirmed that the same config works well in docker. Any suggestion?

**Comment by roxma** [comment]
Try update yarp to the latest version.

**Comment by liuchengxu** [comment]
Thank you. Update nvim-yarp to the latest version solved the issue. Closing...
